export const menuData = [
  {
    id: 'main_features',
    title: 'ОСНОВНОЙ ФУНКЦИОНАЛ',
    collapsible: true,
    items: [
      { id: 'home', icon: 'Home', text: 'Главная', href: '/', enabled: true },
      {
        id: 'placements',
        icon: 'Send',
        text: 'Мои размещения',
        href: '/placements',
        enabled: true,
        selected: true,
      },
      { id: 'stats', icon: 'BarChart3', text: 'Статистика', href: '/stats', enabled: true },
      { id: 'finance', icon: 'Coins', text: 'Финансы', href: '/finance', enabled: false },
      {
        id: 'notifications',
        icon: 'Bell',
        text: 'Уведомления',
        href: '/notifications',
        enabled: true,
      },
      {
        id: 'moderation',
        icon: 'FileCheck',
        text: 'Модерация заявок',
        href: '/moderation',
        enabled: true,
        badge: 100,
      },
      {
        id: 'launch',
        icon: 'Megaphone',
        text: 'Запуск размещений',
        href: '/launch',
        enabled: true,
      },
      {
        id: 'push',
        icon: 'MessageSquare',
        text: 'Push уведомления',
        enabled: true,
        children: [
          { id: 'push_clients', text: 'Для клиентов', href: '/push/clients', enabled: true },
          { id: 'push_publics', text: 'Для пабликов', href: '/push/publics', enabled: true },
        ],
      },
      { id: 'catalog', icon: 'List', text: 'Каталог пабликов', href: '/catalog', enabled: true },
    ],
  },
  {
    id: 'service_work',
    title: 'РАБОТА С СЕРВИСОМ',
    collapsible: true,
    items: [
      { id: 'users', icon: 'Users', text: 'Пользователи', href: '/users', enabled: true },
      { id: 'pages', icon: 'Files', text: 'Страницы', href: '/pages', enabled: true },
      { id: 'modules', icon: 'Component', text: 'Модули', href: '/modules', enabled: true },
      {
        id: 'appearance',
        icon: 'MonitorCog',
        text: 'Внешний вид',
        href: '/appearance',
        enabled: true,
      },
      { id: 'marketing', icon: 'TrendingUp', text: 'Маркетинг', href: '/marketing', enabled: true },
      {
        id: 'analytics',
        icon: 'BarChartHorizontal',
        text: 'Аналитика',
        href: '/analytics',
        enabled: true,
      },
      {
        id: 'crm',
        icon: 'Network',
        text: 'CRM - Система',
        href: '/crm',
        enabled: true,
        style: 'text-blue-500',
      },
      {
        id: 'client_cabinet',
        icon: 'ClipboardCheck',
        text: 'Кабинет клиентов',
        href: '/clients',
        enabled: true,
      },
      {
        id: 'public_cabinet',
        icon: 'ClipboardCheck',
        text: 'Кабинет пабликов',
        href: '/publics',
        enabled: true,
      },
      {
        id: 'planner',
        icon: 'Paperclip',
        text: 'Planer Pabliki',
        href: '/planner',
        enabled: true,
        style: 'text-blue-500',
      },
    ],
  },
];
